### PR TITLE
remove depwarns and use newer travis

### PR DESCRIPTION
**Pull request by SimonDanisch**
Maybe also activate Coveralls? It's just two clicks away now ;)

### CODE REVIEW

**Comment by randyzwitch** [comment]
So it looks like Coveralls is activated? Do you mean just put the badge in the README.

Thanks for doing this (I see you did a PR for Twitter too). I've been spending so much time on visualization, I haven't done anything for this package in a while.

**Comment by SimonDanisch** [comment]
It does look like it! Well then it should be really just about the badge.

**Comment by randyzwitch** [comment]
Added it to README, tagged new version and pushed to METADATA for PR

**Comment by SimonDanisch** [comment]
Great! Thanks a lot :)

**Pull request merged**
