### PR TITLE
Update for Nettle API breakage

### LINKED ISSUE #7: Nettle API breakage
[Nettle](https://github.com/staticfloat/Nettle.jl) has just broken its API significantly, in order to be much more precompile-friendly.  The big takeaway is that methods such as `md5_hash(data)` should be mapped to `digest("md5", data)`, there are no more auto-generated types for hashes, and internally the code is a little easier to grok.  This new version of `Nettle.jl` has not been released yet, I will make every effort to ensure that dependent packages such as this one have a chance to adapt before releasing the new version.

### PR DESCRIPTION
**Pull request by staticfloat**
This should close #7.  My editor (I'm trying out Atom) is a little overzealous with the space-at-end-of-line removals.  If you don't like that, let me know and I'll remove those changes.

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks. There is one error from Travis:
`ERROR: LoadError: UndefVarError: digest not defined`

**Comment by tkelman** [comment]
Would be good to put in the `Nettle 0.2` version requirement as well, which should pass after the metadata tag gets merged

**Comment by randyzwitch** [comment]
In the future, I think we're going to need a better method of doing things like this.

```julia

julia> Pkg.publish()
INFO: Validating METADATA
ERROR: packages with unsatisfiable requirements found:
    OAuth v0.3.0 – no valid versions exist for package Nettle

 in error at error.jl:21
 in check_metadata at pkg/entry.jl:635
 in publish at pkg/entry.jl:372
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in publish at pkg.jl:61

```

Not that I don't believe this PR will worked, but merging in failing changes and then not being able to publish to METADATA doesn't feel particularly good.

**Comment by tkelman** [comment]
That is unfortunate. Maybe breaking changes should be accompanied by adding upper bounds for existing tagged versions of reverse deps. So users of Oauth would stay on previous versions of nettle until a tag of oauth is ready that can use the new nettle

**Comment by staticfloat** [comment]
I agree with you randy. Perhaps a better way to do this next time would be for me to provide a compatibility layer in one version, and then deprecate that layer in the next version, but this change was so small I didnt think it warranted the full approach. But I agree, this didn't feel particularly smooth.

**Comment by randyzwitch** [comment]
No worries, this was still easier than submitting a package to CRAN ;)

**Pull request merged**
