### PR TITLE
Refactor several methods and elaborate tests

### PR DESCRIPTION
**Pull request by jbn**
I chose not to squash this commit. The changes were pretty isolatable; the individual commit messages are easier to read; and, a few have message bodies with references.

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks for doing this! Very thorough.

My only concern is that your changes will break Twitter.jl at minimum; can you either add deprecation warnings and/or update Twitter.jl as well?

**Comment by jbn** [comment]
I didn't realize `Twitter.jl` used any of the methods that I appended `!` to. I'll take a look and update in the AM.

**Comment by randyzwitch** [comment]
I don't know for sure that it will cause breakage, I just presumed it would since you appended ! to some of the functions.

**Comment by jbn** [comment]
I added the deprecation warnings. Ignoring `Twitter.jl`, you're right -- it's bad to break the exported API without warning. Happily though, `Twitter.jl` used neither of the renames. It worked without alteration on 0.4-RC1. 

It failed on 0.3, for reasons (I think) unrelated to `OAuth.jl`. It believe it is due to the recent changes to `Requests.jl` and `HttpParser.jl`. Actually, the latter is explicitly targeting a 0.4 minimum now. I'll open an Issue on `Twitter.jl` in a bit.

**Comment by jbn** [comment]
Oh. Sorry. I just noticed your requiring 0.4 on `Twitter.jl`, anyway. PR ready for merge!

**Comment by randyzwitch** [comment]
Merged, bumped to v0.2 and pushed to METADATA. Thanks!

**Comment by jbn** [comment]
Excellent. A PR that ends in a bump is oh so satisfying!

**Pull request merged**
